name: Build Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ vars.DEPLOY_WITH_DOCKER }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - name: Install PHP dependencies with Composer
        uses: php-actions/composer@v6
        with:
          php_version: '8.1'
          version: 2.x

      - name: Run tests
        run: npm test

      - name: Build theme
        run: npm run build:prod

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/sparkbox/sparkpress:latest
          docker push ghcr.io/sparkbox/sparkpress:latest
